# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nikename',
            field=models.CharField(max_length=32, verbose_name='\u6635\u79f0'),
        ),
    ]
