# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170424_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default=0, max_length=11, verbose_name='\u624b\u673a'),
            preserve_default=False,
        ),
    ]
