# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mynews',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(max_length=10)),
                ('weburl', models.CharField(max_length=100, unique=True)),
                ('mobileurl', models.CharField(max_length=100, unique=True)),
                ('pic', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=20)),
                ('src', models.CharField(max_length=10)),
                ('savepath', models.CharField(max_length=100)),
            ],
        ),
    ]
